version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: djitsotsu_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5543:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: djitsotsu_redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6390:6379"
    volumes:
      - redis_data:/data

  cassandra:
    image: cassandra:4.1
    container_name: djitsostu_cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_DC: "dc1"
      CASSANDRA_ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"
    networks:
      - djitsostu_net

volumes:
  postgres_data:
  redis_data:

networks:
  djitsostu_net:
    driver: bridge